name: metaballs
description: A metaballs implementation for flutter using webgl on the web and the shader package on other devices
version: 1.4.2
homepage: https://github.com/T99Rots/flutter_metaballs

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
  path: ^1.8.2

flutter:
  shaders:
    - shaders/flutter/metaballs.frag
