#version 320 es

precision highp float;

layout(location = 0) out vec4 fragColor;

// define uniforms:
layout(location = 0) uniform float time;
layout(location = 1) uniform float minimumGlowSum;
layout(location = 2) uniform float glowIntensity;
layout(location = 3) uniform float metaballs;

// Why are these defined seperatly? Because when using a vec3[138] the shader when loading in throws
// "Not a supported op". The only place i've seen arrays being using in the flutter engine is in
// https://github.com/flutter/engine/blob/main/lib/ui/fixtures/shaders/general_shaders/uniform_arrays.frag
// but here opengl #version 100 core is used which is not supported by the shader package compiler
// if you know a fix to this issue feel free to make a pr
layout(location = 4) uniform vec3 metaball1;
layout(location = 5) uniform vec3 metaball2;
layout(location = 6) uniform vec3 metaball3;
layout(location = 7) uniform vec3 metaball4;
layout(location = 8) uniform vec3 metaball5;
layout(location = 9) uniform vec3 metaball6;
layout(location = 10) uniform vec3 metaball7;
layout(location = 11) uniform vec3 metaball8;
layout(location = 12) uniform vec3 metaball9;
layout(location = 13) uniform vec3 metaball10;
layout(location = 14) uniform vec3 metaball11;
layout(location = 15) uniform vec3 metaball12;
layout(location = 16) uniform vec3 metaball13;
layout(location = 17) uniform vec3 metaball14;
layout(location = 18) uniform vec3 metaball15;
layout(location = 19) uniform vec3 metaball16;
layout(location = 20) uniform vec3 metaball17;
layout(location = 21) uniform vec3 metaball18;
layout(location = 22) uniform vec3 metaball19;
layout(location = 23) uniform vec3 metaball20;
layout(location = 24) uniform vec3 metaball21;
layout(location = 25) uniform vec3 metaball22;
layout(location = 26) uniform vec3 metaball23;
layout(location = 27) uniform vec3 metaball24;
layout(location = 28) uniform vec3 metaball25;
layout(location = 29) uniform vec3 metaball26;
layout(location = 30) uniform vec3 metaball27;
layout(location = 31) uniform vec3 metaball28;
layout(location = 32) uniform vec3 metaball29;
layout(location = 33) uniform vec3 metaball30;
layout(location = 34) uniform vec3 metaball31;
layout(location = 35) uniform vec3 metaball32;
layout(location = 36) uniform vec3 metaball33;
layout(location = 37) uniform vec3 metaball34;
layout(location = 38) uniform vec3 metaball35;
layout(location = 39) uniform vec3 metaball36;
layout(location = 40) uniform vec3 metaball37;
layout(location = 41) uniform vec3 metaball38;
layout(location = 42) uniform vec3 metaball39;
layout(location = 43) uniform vec3 metaball40;
layout(location = 44) uniform vec3 metaball41;
layout(location = 45) uniform vec3 metaball42;
layout(location = 46) uniform vec3 metaball43;
layout(location = 47) uniform vec3 metaball44;
layout(location = 48) uniform vec3 metaball45;
layout(location = 49) uniform vec3 metaball46;
layout(location = 50) uniform vec3 metaball47;
layout(location = 51) uniform vec3 metaball48;
layout(location = 52) uniform vec3 metaball49;
layout(location = 53) uniform vec3 metaball50;
layout(location = 54) uniform vec3 metaball51;
layout(location = 55) uniform vec3 metaball52;
layout(location = 56) uniform vec3 metaball53;
layout(location = 57) uniform vec3 metaball54;
layout(location = 58) uniform vec3 metaball55;
layout(location = 59) uniform vec3 metaball56;
layout(location = 60) uniform vec3 metaball57;
layout(location = 61) uniform vec3 metaball58;
layout(location = 62) uniform vec3 metaball59;
layout(location = 63) uniform vec3 metaball60;
layout(location = 64) uniform vec3 metaball61;
layout(location = 65) uniform vec3 metaball62;
layout(location = 66) uniform vec3 metaball63;
layout(location = 67) uniform vec3 metaball64;
layout(location = 68) uniform vec3 metaball65;
layout(location = 69) uniform vec3 metaball66;
layout(location = 70) uniform vec3 metaball67;
layout(location = 71) uniform vec3 metaball68;
layout(location = 72) uniform vec3 metaball69;
layout(location = 73) uniform vec3 metaball70;
layout(location = 74) uniform vec3 metaball71;
layout(location = 75) uniform vec3 metaball72;
layout(location = 76) uniform vec3 metaball73;
layout(location = 77) uniform vec3 metaball74;
layout(location = 78) uniform vec3 metaball75;
layout(location = 79) uniform vec3 metaball76;
layout(location = 80) uniform vec3 metaball77;
layout(location = 81) uniform vec3 metaball78;
layout(location = 82) uniform vec3 metaball79;
layout(location = 83) uniform vec3 metaball80;
layout(location = 84) uniform vec3 metaball81;
layout(location = 85) uniform vec3 metaball82;
layout(location = 86) uniform vec3 metaball83;
layout(location = 87) uniform vec3 metaball84;
layout(location = 88) uniform vec3 metaball85;
layout(location = 89) uniform vec3 metaball86;
layout(location = 90) uniform vec3 metaball87;
layout(location = 91) uniform vec3 metaball88;
layout(location = 92) uniform vec3 metaball89;
layout(location = 93) uniform vec3 metaball90;
layout(location = 94) uniform vec3 metaball91;
layout(location = 95) uniform vec3 metaball92;
layout(location = 96) uniform vec3 metaball93;
layout(location = 97) uniform vec3 metaball94;
layout(location = 98) uniform vec3 metaball95;
layout(location = 99) uniform vec3 metaball96;
layout(location = 100) uniform vec3 metaball97;
layout(location = 101) uniform vec3 metaball98;
layout(location = 102) uniform vec3 metaball99;
layout(location = 103) uniform vec3 metaball100;
layout(location = 104) uniform vec3 metaball101;
layout(location = 105) uniform vec3 metaball102;
layout(location = 106) uniform vec3 metaball103;
layout(location = 107) uniform vec3 metaball104;
layout(location = 108) uniform vec3 metaball105;
layout(location = 109) uniform vec3 metaball106;
layout(location = 110) uniform vec3 metaball107;
layout(location = 111) uniform vec3 metaball108;
layout(location = 112) uniform vec3 metaball109;
layout(location = 113) uniform vec3 metaball110;
layout(location = 114) uniform vec3 metaball111;
layout(location = 115) uniform vec3 metaball112;
layout(location = 116) uniform vec3 metaball113;
layout(location = 117) uniform vec3 metaball114;
layout(location = 118) uniform vec3 metaball115;
layout(location = 119) uniform vec3 metaball116;
layout(location = 120) uniform vec3 metaball117;
layout(location = 121) uniform vec3 metaball118;
layout(location = 122) uniform vec3 metaball119;
layout(location = 123) uniform vec3 metaball120;
layout(location = 124) uniform vec3 metaball121;
layout(location = 125) uniform vec3 metaball122;
layout(location = 126) uniform vec3 metaball123;
layout(location = 127) uniform vec3 metaball124;
layout(location = 128) uniform vec3 metaball125;
layout(location = 129) uniform vec3 metaball126;
layout(location = 130) uniform vec3 metaball127;
layout(location = 131) uniform vec3 metaball128;
layout(location = 132) uniform vec3 metaball129;
layout(location = 133) uniform vec3 metaball130;
layout(location = 134) uniform vec3 metaball131;
layout(location = 135) uniform vec3 metaball132;
layout(location = 136) uniform vec3 metaball133;
layout(location = 137) uniform vec3 metaball134;
layout(location = 138) uniform vec3 metaball135;
layout(location = 139) uniform vec3 metaball136;
layout(location = 140) uniform vec3 metaball137;
layout(location = 141) uniform vec3 metaball138;

float addSum(vec3 metaball, vec2 coords) {
  float dx = metaball.x - coords.x;
  float dy = metaball.y - coords.y;
  float radius = metaball.z;
  return ((radius * radius) / (dx * dx + dy * dy));
}

vec4 noise(vec4 v){
  // ensure reasonable range
  v = fract(v) + fract(v*1e4) + fract(v*1e-4);
  // seed
  v += vec4(0.12345, 0.6789, 0.314159, 0.271828);
  // more iterations => more random
  v = fract(v*dot(v, v)*123.456);
  v = fract(v*dot(v, v)*123.456);
  return v;
}

float getSum(vec2 coords) {
  float sum = 0.0;
  if(metaballs < 1.0) return sum;
  sum += addSum(metaball1, coords);
  if(metaballs < 2.0) return sum;
  sum += addSum(metaball2, coords);
  if(metaballs < 3.0) return sum;
  sum += addSum(metaball3, coords);
  if(metaballs < 4.0) return sum;
  sum += addSum(metaball4, coords);
  if(metaballs < 5.0) return sum;
  sum += addSum(metaball5, coords);
  if(metaballs < 6.0) return sum;
  sum += addSum(metaball6, coords);
  if(metaballs < 7.0) return sum;
  sum += addSum(metaball7, coords);
  if(metaballs < 8.0) return sum;
  sum += addSum(metaball8, coords);
  if(metaballs < 9.0) return sum;
  sum += addSum(metaball9, coords);
  if(metaballs < 10.0) return sum;
  sum += addSum(metaball10, coords);
  if(metaballs < 11.0) return sum;
  sum += addSum(metaball11, coords);
  if(metaballs < 12.0) return sum;
  sum += addSum(metaball12, coords);
  if(metaballs < 13.0) return sum;
  sum += addSum(metaball13, coords);
  if(metaballs < 14.0) return sum;
  sum += addSum(metaball14, coords);
  if(metaballs < 15.0) return sum;
  sum += addSum(metaball15, coords);
  if(metaballs < 16.0) return sum;
  sum += addSum(metaball16, coords);
  if(metaballs < 17.0) return sum;
  sum += addSum(metaball17, coords);
  if(metaballs < 18.0) return sum;
  sum += addSum(metaball18, coords);
  if(metaballs < 19.0) return sum;
  sum += addSum(metaball19, coords);
  if(metaballs < 20.0) return sum;
  sum += addSum(metaball20, coords);
  if(metaballs < 21.0) return sum;
  sum += addSum(metaball21, coords);
  if(metaballs < 22.0) return sum;
  sum += addSum(metaball22, coords);
  if(metaballs < 23.0) return sum;
  sum += addSum(metaball23, coords);
  if(metaballs < 24.0) return sum;
  sum += addSum(metaball24, coords);
  if(metaballs < 25.0) return sum;
  sum += addSum(metaball25, coords);
  if(metaballs < 26.0) return sum;
  sum += addSum(metaball26, coords);
  if(metaballs < 27.0) return sum;
  sum += addSum(metaball27, coords);
  if(metaballs < 28.0) return sum;
  sum += addSum(metaball28, coords);
  if(metaballs < 29.0) return sum;
  sum += addSum(metaball29, coords);
  if(metaballs < 30.0) return sum;
  sum += addSum(metaball30, coords);
  if(metaballs < 31.0) return sum;
  sum += addSum(metaball31, coords);
  if(metaballs < 32.0) return sum;
  sum += addSum(metaball32, coords);
  if(metaballs < 33.0) return sum;
  sum += addSum(metaball33, coords);
  if(metaballs < 34.0) return sum;
  sum += addSum(metaball34, coords);
  if(metaballs < 35.0) return sum;
  sum += addSum(metaball35, coords);
  if(metaballs < 36.0) return sum;
  sum += addSum(metaball36, coords);
  if(metaballs < 37.0) return sum;
  sum += addSum(metaball37, coords);
  if(metaballs < 38.0) return sum;
  sum += addSum(metaball38, coords);
  if(metaballs < 39.0) return sum;
  sum += addSum(metaball39, coords);
  if(metaballs < 40.0) return sum;
  sum += addSum(metaball40, coords);
  if(metaballs < 41.0) return sum;
  sum += addSum(metaball41, coords);
  if(metaballs < 42.0) return sum;
  sum += addSum(metaball42, coords);
  if(metaballs < 43.0) return sum;
  sum += addSum(metaball43, coords);
  if(metaballs < 44.0) return sum;
  sum += addSum(metaball44, coords);
  if(metaballs < 45.0) return sum;
  sum += addSum(metaball45, coords);
  if(metaballs < 46.0) return sum;
  sum += addSum(metaball46, coords);
  if(metaballs < 47.0) return sum;
  sum += addSum(metaball47, coords);
  if(metaballs < 48.0) return sum;
  sum += addSum(metaball48, coords);
  if(metaballs < 49.0) return sum;
  sum += addSum(metaball49, coords);
  if(metaballs < 50.0) return sum;
  sum += addSum(metaball50, coords);
  if(metaballs < 51.0) return sum;
  sum += addSum(metaball51, coords);
  if(metaballs < 52.0) return sum;
  sum += addSum(metaball52, coords);
  if(metaballs < 53.0) return sum;
  sum += addSum(metaball53, coords);
  if(metaballs < 54.0) return sum;
  sum += addSum(metaball54, coords);
  if(metaballs < 55.0) return sum;
  sum += addSum(metaball55, coords);
  if(metaballs < 56.0) return sum;
  sum += addSum(metaball56, coords);
  if(metaballs < 57.0) return sum;
  sum += addSum(metaball57, coords);
  if(metaballs < 58.0) return sum;
  sum += addSum(metaball58, coords);
  if(metaballs < 59.0) return sum;
  sum += addSum(metaball59, coords);
  if(metaballs < 60.0) return sum;
  sum += addSum(metaball60, coords);
  if(metaballs < 61.0) return sum;
  sum += addSum(metaball61, coords);
  if(metaballs < 62.0) return sum;
  sum += addSum(metaball62, coords);
  if(metaballs < 63.0) return sum;
  sum += addSum(metaball63, coords);
  if(metaballs < 64.0) return sum;
  sum += addSum(metaball64, coords);
  if(metaballs < 65.0) return sum;
  sum += addSum(metaball65, coords);
  if(metaballs < 66.0) return sum;
  sum += addSum(metaball66, coords);
  if(metaballs < 67.0) return sum;
  sum += addSum(metaball67, coords);
  if(metaballs < 68.0) return sum;
  sum += addSum(metaball68, coords);
  if(metaballs < 69.0) return sum;
  sum += addSum(metaball69, coords);
  if(metaballs < 70.0) return sum;
  sum += addSum(metaball70, coords);
  if(metaballs < 71.0) return sum;
  sum += addSum(metaball71, coords);
  if(metaballs < 72.0) return sum;
  sum += addSum(metaball72, coords);
  if(metaballs < 73.0) return sum;
  sum += addSum(metaball73, coords);
  if(metaballs < 74.0) return sum;
  sum += addSum(metaball74, coords);
  if(metaballs < 75.0) return sum;
  sum += addSum(metaball75, coords);
  if(metaballs < 76.0) return sum;
  sum += addSum(metaball76, coords);
  if(metaballs < 77.0) return sum;
  sum += addSum(metaball77, coords);
  if(metaballs < 78.0) return sum;
  sum += addSum(metaball78, coords);
  if(metaballs < 79.0) return sum;
  sum += addSum(metaball79, coords);
  if(metaballs < 80.0) return sum;
  sum += addSum(metaball80, coords);
  if(metaballs < 81.0) return sum;
  sum += addSum(metaball81, coords);
  if(metaballs < 82.0) return sum;
  sum += addSum(metaball82, coords);
  if(metaballs < 83.0) return sum;
  sum += addSum(metaball83, coords);
  if(metaballs < 84.0) return sum;
  sum += addSum(metaball84, coords);
  if(metaballs < 85.0) return sum;
  sum += addSum(metaball85, coords);
  if(metaballs < 86.0) return sum;
  sum += addSum(metaball86, coords);
  if(metaballs < 87.0) return sum;
  sum += addSum(metaball87, coords);
  if(metaballs < 88.0) return sum;
  sum += addSum(metaball88, coords);
  if(metaballs < 89.0) return sum;
  sum += addSum(metaball89, coords);
  if(metaballs < 90.0) return sum;
  sum += addSum(metaball90, coords);
  if(metaballs < 91.0) return sum;
  sum += addSum(metaball91, coords);
  if(metaballs < 92.0) return sum;
  sum += addSum(metaball92, coords);
  if(metaballs < 93.0) return sum;
  sum += addSum(metaball93, coords);
  if(metaballs < 94.0) return sum;
  sum += addSum(metaball94, coords);
  if(metaballs < 95.0) return sum;
  sum += addSum(metaball95, coords);
  if(metaballs < 96.0) return sum;
  sum += addSum(metaball96, coords);
  if(metaballs < 97.0) return sum;
  sum += addSum(metaball97, coords);
  if(metaballs < 98.0) return sum;
  sum += addSum(metaball98, coords);
  if(metaballs < 99.0) return sum;
  sum += addSum(metaball99, coords);
  if(metaballs < 100.0) return sum;
  sum += addSum(metaball100, coords);
  if(metaballs < 101.0) return sum;
  sum += addSum(metaball101, coords);
  if(metaballs < 102.0) return sum;
  sum += addSum(metaball102, coords);
  if(metaballs < 103.0) return sum;
  sum += addSum(metaball103, coords);
  if(metaballs < 104.0) return sum;
  sum += addSum(metaball104, coords);
  if(metaballs < 105.0) return sum;
  sum += addSum(metaball105, coords);
  if(metaballs < 106.0) return sum;
  sum += addSum(metaball106, coords);
  if(metaballs < 107.0) return sum;
  sum += addSum(metaball107, coords);
  if(metaballs < 108.0) return sum;
  sum += addSum(metaball108, coords);
  if(metaballs < 109.0) return sum;
  sum += addSum(metaball109, coords);
  if(metaballs < 110.0) return sum;
  sum += addSum(metaball110, coords);
  if(metaballs < 111.0) return sum;
  sum += addSum(metaball111, coords);
  if(metaballs < 112.0) return sum;
  sum += addSum(metaball112, coords);
  if(metaballs < 113.0) return sum;
  sum += addSum(metaball113, coords);
  if(metaballs < 114.0) return sum;
  sum += addSum(metaball114, coords);
  if(metaballs < 115.0) return sum;
  sum += addSum(metaball115, coords);
  if(metaballs < 116.0) return sum;
  sum += addSum(metaball116, coords);
  if(metaballs < 117.0) return sum;
  sum += addSum(metaball117, coords);
  if(metaballs < 118.0) return sum;
  sum += addSum(metaball118, coords);
  if(metaballs < 119.0) return sum;
  sum += addSum(metaball119, coords);
  if(metaballs < 120.0) return sum;
  sum += addSum(metaball120, coords);
  if(metaballs < 121.0) return sum;
  sum += addSum(metaball121, coords);
  if(metaballs < 122.0) return sum;
  sum += addSum(metaball122, coords);
  if(metaballs < 123.0) return sum;
  sum += addSum(metaball123, coords);
  if(metaballs < 124.0) return sum;
  sum += addSum(metaball124, coords);
  if(metaballs < 125.0) return sum;
  sum += addSum(metaball125, coords);
  if(metaballs < 126.0) return sum;
  sum += addSum(metaball126, coords);
  if(metaballs < 127.0) return sum;
  sum += addSum(metaball127, coords);
  if(metaballs < 128.0) return sum;
  sum += addSum(metaball128, coords);
  if(metaballs < 129.0) return sum;
  sum += addSum(metaball129, coords);
  if(metaballs < 130.0) return sum;
  sum += addSum(metaball130, coords);
  if(metaballs < 131.0) return sum;
  sum += addSum(metaball131, coords);
  if(metaballs < 132.0) return sum;
  sum += addSum(metaball132, coords);
  if(metaballs < 133.0) return sum;
  sum += addSum(metaball133, coords);
  if(metaballs < 134.0) return sum;
  sum += addSum(metaball134, coords);
  if(metaballs < 135.0) return sum;
  sum += addSum(metaball135, coords);
  if(metaballs < 136.0) return sum;
  sum += addSum(metaball136, coords);
  if(metaballs < 137.0) return sum;
  sum += addSum(metaball137, coords);
  if(metaballs < 138.0) return sum;
  sum += addSum(metaball138, coords);
  return sum;
}

void main(){
  vec2 coords = gl_FragCoord.xy;
  float sum = getSum(coords);

  if(sum >= 1.0) {
    fragColor = vec4(1,1,1,1);
  } else if(sum > minimumGlowSum) {
    float n = ((sum - minimumGlowSum) / (1.0 - minimumGlowSum)) * glowIntensity;
    
    fragColor = vec4(n) + ((noise(vec4(coords, time, 0.0)) - 0.5) / 255.0);
  } else {
    fragColor = vec4(0, 0, 0, 0);
  }
}